"""users table

Revision ID: a540e0c9374e
Revises: 
Create Date: 2019-10-17 15:36:20.364552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a540e0c9374e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uname', sa.String(length=64), nullable=True),
    sa.Column('twofa', sa.String(length=64), nullable=True),
    sa.Column('pword', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_twofa'), 'user', ['twofa'], unique=True)
    op.create_index(op.f('ix_user_uname'), 'user', ['uname'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_uname'), table_name='user')
    op.drop_index(op.f('ix_user_twofa'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
